# Bitcoin Core Configuration File

# Network
server=1
txindex=1
prune=0

# RPC Configuration
rpcuser=${BITCOIN_RPC_USER}
rpcpassword=${BITCOIN_RPC_PASSWORD}
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0

# Performance
dbcache=2048
maxmempool=300
maxconnections=40
maxuploadtarget=5000

# Logging
debug=rpc
debug=net
debug=tor
debug=mempool
debug=coindb
debug=qt
debug=leveldb 